using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Vipusknaya4
{
    public partial class Form2 : Form
    {
        public Form2()
        {
            InitializeComponent();
        }
        Brush col;
        bool _data;
        private void Form2_Load(object sender, EventArgs e)
        {
            int h = 50, w = 50;
            PictureBox x1 = new PictureBox();
            x1.BackColor = Color.AliceBlue;
            x1.Height = h;x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.AntiqueWhite;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Aqua;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Aquamarine;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Azure;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Beige;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Bisque;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Black;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.BlanchedAlmond;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Blue;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.BlueViolet;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Brown;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.BurlyWood;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.CadetBlue;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Chartreuse;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Chocolate;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Coral;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.CornflowerBlue;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Cornsilk;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Crimson;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Cyan;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DarkBlue;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DarkCyan;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DarkGoldenrod;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DarkGray;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DarkGreen;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DarkKhaki;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DarkMagenta;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DarkOliveGreen;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DarkOrange;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DarkOrchid;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DarkRed;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DarkSalmon;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DarkSeaGreen;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DarkSlateBlue;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DarkSlateGray;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DarkTurquoise;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DarkViolet;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DeepPink;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DeepSkyBlue;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DimGray;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.DodgerBlue;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Firebrick;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.FloralWhite;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.ForestGreen;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Fuchsia;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Gainsboro;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.GhostWhite;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Gold;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Goldenrod;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Gray;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Green;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.GreenYellow;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Honeydew;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.HotPink;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.IndianRed;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Indigo;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Ivory;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Khaki;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Lavender;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.LavenderBlush;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.LawnGreen;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.LemonChiffon;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.LightBlue;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.LightCoral;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.LightCyan;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.LightGoldenrodYellow;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.LightGray;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.LightGreen;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.LightPink;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.LightSalmon;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.LightSeaGreen;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.LightSkyBlue;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.LightSlateGray;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.LightSteelBlue;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.LightYellow;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Lime;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.LimeGreen;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Linen;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Magenta;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.Maroon;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.MediumAquamarine;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.MediumBlue;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
            x1 = new PictureBox();
            x1.BackColor = Color.MediumOrchid;
            x1.Height = h; x1.Width = w;
            x1.BorderStyle = BorderStyle.Fixed3D;
            x1.Click += new EventHandler(this.x1_click);
            flowLayoutPanel1.Controls.Add(x1);
        }
        void x1_click(Object sender,EventArgs e)
        {
            PictureBox x = (PictureBox)sender;
            pictureBox1.BackColor = x.BackColor;
            col = new SolidBrush(x.BackColor);
        }

        private void button1_Click(object sender, EventArgs e)
        {
            _data = true;
            this.Close();
        }

        private void button2_Click(object sender, EventArgs e)
        {
            _data = false;
            this.Close();
        }

        public Brush data
        {
            get
            {
                return col;
            }
        }
        public bool data2
        {
            get
            {
                return _data;
            }
        }

    }
}
